apiVersion: v1
kind: ConfigMap
metadata:
  name: convoscore-grafana-datasources
  labels:
    {{- include "convoscore.labels" (dict "component" "grafana") | nindent 4 }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://convoscore-prometheus:{{ .Values.prometheus.port }}
        isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: convoscore-grafana-dashboard-provider
  labels:
    {{- include "convoscore.labels" (dict "component" "grafana") | nindent 4 }}
data:
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: convoscore
        folder: ""
        type: file
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: convoscore-grafana-dashboard-json
  labels:
    {{- include "convoscore.labels" (dict "component" "grafana") | nindent 4 }}
data:
  convoscore.json: |
{{ .Files.Get "dashboards/convoscore.json" | indent 4 }}
